export default {
  customPortfolio: [
    [
      'Fondo Ahorro Dinámico',
      '',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
    [
      'Fondo Balanceado Crecimiento',
      '',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
    [
      'Fondo Balanceado Moderado',
      '',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
    [
      'Fondo Latino América',
      '',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
    [
      'Fondo Estados Unidos',
      '',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
  ],
  funds: {
    aggressive: [[
      'Fondo Dinámico Agresivo Serie APV',
      '100%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ]],
    balanced: [[
      'Fondo Dinámico Balanceado Serie APV',
      '100%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ]],
    conservative: [[
      'Fondo Dinámico Conservador Serie APV',
      '100%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ]],
    increase: [[
      'Fondo Dinámico Crecimiento Serie APV',
      '100%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ]],
    moderate: [[
      'Fondo Dinámico Moderado Serie APV',
      '100%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ]],
  },
  fundsChangeHistory: [
    {
      number: '48617',
      status: 'posted',
      date: '16/04/2019',
      before: [
        ['Fondo Dinámico', '40%'],
        ['Fondo Crecimiento', '35%'],
        ['Fondo Asia', '10%'],
        ['Fondo Estados Unidos', '10%'],
        ['Fondo Conservador', '5%'],
      ],
      result: [
        ['Fondo Dinámico', '40%'],
        ['Fondo Crecimiento', '35%'],
        ['Fondo Asia', '10%'],
        ['Fondo Estados Unidos', '10%'],
        ['Fondo Conservador', '5%'],
      ],
    },
    {
      number: '48434',
      status: 'posted',
      date: '10/04/2019',
      before: [
        ['Fondo Dinámico', '40%'],
        ['Fondo Crecimiento', '35%'],
        ['Fondo Asia', '10%'],
        ['Fondo Estados Unidos', '10%'],
        ['Fondo Conservador', '5%'],
      ],
      result: [
        ['Fondo Dinámico', '40%'],
        ['Fondo Crecimiento', '35%'],
        ['Fondo Asia', '10%'],
        ['Fondo Estados Unidos', '10%'],
        ['Fondo Conservador', '5%'],
      ],
    },
    {
      number: '45349',
      status: 'posted',
      date: '21/11/2018',
      before: [
        ['Fondo Dinámico', '40%'],
        ['Fondo Crecimiento', '35%'],
        ['Fondo Asia', '10%'],
        ['Fondo Estados Unidos', '10%'],
        ['Fondo Conservador', '5%'],
      ],
      result: [
        ['Fondo Dinámico', '40%'],
        ['Fondo Crecimiento', '35%'],
        ['Fondo Asia', '10%'],
        ['Fondo Estados Unidos', '10%'],
        ['Fondo Conservador', '5%'],
      ],
    },
  ],
  fundsCurrentPortfolio: [
    [
      'Fondo Asia',
      '22%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
    [
      'Fondo Estados Unidos',
      '11%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
    [
      'Fondo Latinoamérica',
      '27%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
    [
      'Fondo Ahorro Dinámico',
      '19%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
    [
      'Fondo Crecimiento',
      '21%',
      '$1.852,95',
      '0,54%',
      '4,98%',
    ],
  ],
  statements: {
    options: {
      months: [
        '01/2020',
        '02/2020',
        '03/2020',
        '04/2020',
        '05/2020',
      ],
      years: [
        '2020',
        '2019',
        '2018',
        '2017',
        '2016',
        '2015',
      ],
    },
  },
  contractor: {
    name: 'Juan Cabezas Reyes',
    email: 'jcabezas@gmail.com',
    id: '16.481.214-3',
  },
  policy: {
    number: '11173900',
    title: 'Seguro Vida Ahorro',
    status: 'valid',
    permanency: {
      years: 6,
      months: 8,
    },
    value: 'UF 29,39',
    lastValue: [{ currency: 'uf', amount: 243.96 }, { currency: 'usd', amount: 6762.537 }],
    historicalValue: {
      lastBalance: {
        date: '28/02/2020',
      },
    },
    date: '20/04/2019',
    coverageValue: 'UF 500',
    mainBeneficiary: {
      coverages: [{
        nameId: 'death',
        amount: '1500',
        currency: 'uf',
      }],
      detailedCoverages: [
        [
          'Fallecimiento',
          'Condicionado CAD 292XXX',
          'Capital UF 1.500,00',
        ],
        [{ text: 'Reembolso de Prestaciones Médicas', tooltip: 'something' }, 'Condicionado CAD 292XXX'],
        [{ text: 'Oncológico', tooltip: 'something' }, 'Condicionado CAD 292XXX'],
        [{ text: 'Atención Telefónica Médico', tooltip: 'something' }],
        [{ text: 'Accidentes', tooltip: 'something' }, 'Monto Asegurado UF 1.500,00'],
      ],
    },
  },
  policyValueHistory: [
    {
      date: '04/2020',
      balance: '134,37',
      currency: 'UF',
      details: [
        {
          date: '30/04/2020',
          description: 'Cambio de valor del mercado',
          value: 'UF 0,07',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Prima Referen.',
          value: 'UF 0,05',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Prima Recaud.',
          value: 'UF 0,03',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Cargo Fijo',
          value: 'UF 0,04',
        },
        {
          date: '30/04/2020',
          description: 'Depósito APV',
          value: 'UF 0,04',
        },
      ],
    },
    {
      date: '03/2020',
      balance: '121,37',
      currency: 'UF',
      details: [
        {
          date: '30/04/2020',
          description: 'Cambio de valor del mercado',
          value: 'UF 0,07',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Prima Referen.',
          value: 'UF 0,05',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Prima Recaud.',
          value: 'UF 0,03',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Cargo Fijo',
          value: 'UF 0,04',
        },
        {
          date: '30/04/2020',
          description: 'Depósito APV',
          value: 'UF 0,04',
        },
      ],
    },
    {
      date: '02/2020',
      balance: '111,92',
      currency: 'UF',
      details: [
        {
          date: '30/04/2020',
          description: 'Cambio de valor del mercado',
          value: 'UF 0,07',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Prima Referen.',
          value: 'UF 0,05',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Prima Recaud.',
          value: 'UF 0,03',
        },
        {
          date: '30/04/2020',
          description: 'Gto Gestión: Cargo Fijo',
          value: 'UF 0,04',
        },
        {
          date: '30/04/2020',
          description: 'Depósito APV',
          value: 'UF 0,04',
        },
      ],
    },
  ],
  policyBalance: [
    {
      description: 'Depósito APV B > 16-12-11',
      currency: 'UF',
      balance: '110,40',
      details: [
        [
          'Fecha Ahorro Dinámico',
          '657,69',
          'UF 0,07',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Balanceado Moderado',
          '696,09',
          'UF 0,06',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Asia',
          '433,92',
          'UF 0,04',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Estados Unidos',
          '657,69',
          'UF 0,07',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Crecimiento',
          '433,92',
          'UF 0,03',
          '$1.218.653',
          'UF 43,67',
        ],
      ],
    },
    {
      description: 'Depósito APV - B',
      currency: 'UF',
      balance: '110,40',
      details: [
        [
          'Fecha Ahorro Dinámico',
          '657,69',
          'UF 0,07',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Balanceado Moderado',
          '696,09',
          'UF 0,06',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Asia',
          '433,92',
          'UF 0,04',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Estados Unidos',
          '657,69',
          'UF 0,07',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Crecimiento',
          '433,92',
          'UF 0,03',
          '$1.218.653',
          'UF 43,67',
        ],
      ],
    },
    {
      description: 'Otra cuenta',
      currency: 'UF',
      balance: '110,40',
      details: [
        [
          'Fecha Ahorro Dinámico',
          '657,69',
          'UF 0,07',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Balanceado Moderado',
          '696,09',
          'UF 0,06',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Asia',
          '433,92',
          'UF 0,04',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Estados Unidos',
          '657,69',
          'UF 0,07',
          '$1.218.653',
          'UF 43,67',
        ],
        [
          'Fecha Crecimiento',
          '433,92',
          'UF 0,03',
          '$1.218.653',
          'UF 43,67',
        ],
      ],
    },
  ],
};
