export default {
  paramClientId: 1,
  accounts: [],
  interestRate: '',
  installment: '',
  annualRate: '',
  monthlyAmount: '',
  totalLoanAmount: '',
  loanCosts: '',
  percentageLoanCosts: '',
  cae: '',
  stampTax: '',
  notaryFee: '',
  monthlyRate: '',
  disgraceInsurance: '',
  unemploymentInsurance: '',

  // new items
  showSettingsView: true,
  amount: 0,
  monthsGrace: 0,
  account: null,
  payments: 6,
  disgrace: true,
  unemployment: true,
  showSimulationDetails: false,
};
